### ISSUE TITLE
Bomb flickers

### ISSUE THREAD

**Issue by Yeehawlerz101** [gmastergreatee/OneshotsGlowHack#1]
I know you didn't write the code but, when standing the the bomb after its planted there is a slight flicker on my end. Plus Kudos to you for updating this.
My Specs (In case its just on my end)
Processor(s) = Intel(R) Core(TM) i7 CPU 920 @ 2.67GHz
Optical Drive(s) = LITE-ON DVDRW LH-20A1L ATA Device
HardDrive(s) = TOSHIBA DT01ACA100 ATA Device (931.51 GB)
Motherboard = ASUSTeK Computer INC. P6T DELUXE
Memory (ram) = (Total: 6 GB) 2 GB 1066 (ModulePartNumber00), 2 GB 1066 (ModulePartNumber02), 2 GB 1066 (ModulePartNumber04)
Video Card(s) = NVIDIA GeForce GTX 960 (4 GB Video Ram)

**Comment by gmastergreatee** [comment]
What this "glowhack" actually does is write values(glow+health related) on the csgo.exe's memory. The game on the other hand tries again & again to reset the values to default(i.e. 0). Well, I'm just guessing here that the flicker is caused by the slow write speed of the hack because it has to write on multiple places in "weapon's glow mode". This may be because of high ram usage at the moment.

I'll dig deeper into the situation later.
Thanks for reporting. 😃

**Comment by gmastergreatee** [comment]
I use i7-3740qm(RAM 12gigs,4gb Nvidia), & it flickers here sometimes in weapons glow mode, so the thing I mentioned above must be the reason for the problem.

I'll try to customize it even more, i.e. the option to set glow to particular type of weapon/grenades, so that users facing this issue can selectively choose what to glow.
Cya later
