### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by k9521** [gmastergreatee/OneshotsGlowHack#2]
Hi Bro.
I would like to use your's source code, but i have problem....
File: Hprocess.h
Line: 38, 80 - "Warchar*" does not match the type parameter "const char*"
Line: 98, 122 -  "const char*" does not match the type parameter "LPCWST"
I use VS2017.
So, I fixed these errors(I write type conversion).
Now program does not find "client.dll".
So it can not work any more ...
Have you any solution?

**Comment by gmastergreatee** [comment]
Did you check if the __"Character Set"__ used in the project is set to __"Multi-Byte"__?

**Comment by k9521** [comment]
Thank you.
That was helpful, but i have one more problem anymore.
So, When module 'GetModuleNamePointer' searching "cliend.dll" program is stop.
I print object 'lpModuleEntry.szModule.'

> csgo.exe
> ntdll.dll
> wow64.dll
> wow64win.dll
> wow64cpu.dll
> csgo.exe
>.
>.
>.

Don't worry, i write this to lern myself.
I will not public yours code/app.

**Comment by gmastergreatee** [comment]
So, from what I think, the above error must be because of privileges. Make sure that you run VS with admin privileges, so the hack would also run with admin rights.

Ah, & make sure you spell it correctly, not "cliend.dll", it's __"client.dll"__.

BTW, the code is already public. I just requested you to respect contributors, well that's up to you. 😄
